### ISSUE TITLE
Source files lost?

### ISSUE THREAD

**Issue by TaruMuranen** [slowkow/proxysnps#5]
2018-04-25 14.15 EEST 
running:
d <- get_proxies(chrom = "12", pos = 583090, window_size = 1e5, pop = "AFR")
gives error message:
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input

get_proxies() worked all right about 24h earlier.

**Comment by mreppell** [comment]
They seem to have moved to: http://bochet.gcc.biostat.washington.edu/beagle/1000_Genomes_phase3_v5a/vcf.b37/

When I went in to debug in the get_proxies function and substituted that for the current url: 
 http://bochet.gcc.biostat.washington.edu/beagle/1000_Genomes_phase3_v5a/individual_chromosomes/

The package would work again

**Comment by slowkow** [comment]
@TaruMuranen Thanks for reporting this issue!

@mreppell Thanks for pointing out the fix!

Here's an example I tried to test if it is working after changing the BEAGLE URL:

```r
library(proxysnps)
d <- get_proxies(chrom = "12", pos = 583090, window_size = 1e5, pop = "AFR")
head(d)
```
```
    CHROM    POS          ID REF ALT   ALT_FREQ        R R.squared  D.prime CHOSEN
663    12 583090  rs11063140   A   G 0.15506808 1.000000  1.000000 1.000000   TRUE
685    12 584423  rs10849066   A   G 0.23071104 0.772357  0.596535 0.987318  FALSE
661    12 583003  rs11063139   C   T 0.16868381 0.738975  0.546084 0.777021  FALSE
678    12 584054 rs145345255   G   A 0.07791225 0.655136  0.429203 0.965528  FALSE
682    12 584354  rs10849065   G   T 0.18759455 0.613153  0.375957 0.687769  FALSE
711    12 586815  rs58254236   C   T 0.08396369 0.601214  0.361458 0.850726  FALSE
```

```r
plot(d$POS, d$R.squared, main="rs11063140", xlab="Position", ylab=bquote("R"^2))
```
![image](https://user-images.githubusercontent.com/209714/39257758-488f492c-4880-11e8-9569-0e84354f081c.png)

Please try re-installing the package:

```r
devtools::install_github("slowkow/proxysnps")
```

**Comment by seafloor** [comment]
Just to add that I got the same error when the files got moved, and that the latest commit solved the issue. Thanks for the quick fix!
