### ISSUE TITLE
Incorrect URL for 1000 Genomes phase3 data

### ISSUE THREAD

**Issue by sjfandrews** [slowkow/proxysnps#7]
Hi, the URL for the 1000 genomes phase 3 data hosted by Brian Browning has changed. Currently, the URL in get_vcf is set as 

http://bochet.gcc.biostat.washington.edu/beagle/1000_Genomes_phase3_v5a/vcf.b37/chr16.1kg.phase3.v5a.vcf.gz

The correct URL is now (vcf.b37 -> b37.vcf)

http://bochet.gcc.biostat.washington.edu/beagle/1000_Genomes_phase3_v5a/b37.vcf/chr16.1kg.phase3.v5a.vcf.gz

Thanks 
Shea

**Comment by slowkow** [comment]
Thanks! We ran into this in issue #5 and I'm surprised to see that the URL changed again so soon.

I think it is time to stop hard-coding this URL... I will try to give some time to this package soon, but I have other priorities right now.

**Comment by sjfandrews** [comment]
Thanks, just confirming that the URL is now working again.
